### ISSUE TITLE
DynamicObject w/ index access throws ParseException

### ISSUE THREAD

**Issue by marcOcram** [davideicardi/DynamicExpresso#127]
Hello,

I tried to access a dynamic object by index and the library seems to be unable to parse the expression on .NET Core 3.1 and .NET 4.7.2.

```csharp
using DynamicExpresso;
using System;
using System.Dynamic;
using System.Collections.Generic;

public class Program
{
	public class Globals {
		private readonly DynamicIndexAccess _values = new DynamicIndexAccess();
		
		public dynamic Values { get { return _values; } }
	}
	
	public class DynamicIndexAccess : DynamicObject {
		private readonly IReadOnlyDictionary<string, object> _values;

		public DynamicIndexAccess()
		{
			var values = new Dictionary<string, object>();
			values.Add("Hello", "Hello World!");
			_values = values;
		}

		public override bool TryGetIndex(GetIndexBinder binder, object[] indexes, out object result)
		{
			return _values.TryGetValue((string)indexes[0], out result);
		}

		public override bool TryGetMember(GetMemberBinder binder, out object result)
		{
			return _values.TryGetValue(binder.Name, out result);
		}
	}
	
	public static void Main()
	{
		Globals globals = new Globals();
		Interpreter interpreter = new Interpreter()
			.SetVariable("Values", globals.Values);
		// runs
		Console.WriteLine(globals.Values.Hello);
		// runs
		Console.WriteLine(interpreter.Eval<string>("Values.Hello"));
		// runs
		Console.WriteLine(globals.Values["Hello"]);
		// fails
		Console.WriteLine(interpreter.Eval<string>("Values[\"Hello\"]"));
	}
}
```
Stacktrace
```
DynamicExpresso.Exceptions.ParseException: No applicable indexer exists in type 'DynamicIndexAccess' (at index 6).
   at DynamicExpresso.Parsing.Parser.ParseElementAccess(Expression expr)
   at DynamicExpresso.Parsing.Parser.ParsePrimary()
   at DynamicExpresso.Parsing.Parser.ParseUnary()
   at DynamicExpresso.Parsing.Parser.ParseMultiplicative()
   at DynamicExpresso.Parsing.Parser.ParseAdditive()
   at DynamicExpresso.Parsing.Parser.ParseTypeTesting()
   at DynamicExpresso.Parsing.Parser.ParseComparison()
   at DynamicExpresso.Parsing.Parser.ParseLogicalAnd()
   at DynamicExpresso.Parsing.Parser.ParseLogicalXor()
   at DynamicExpresso.Parsing.Parser.ParseLogicalOr()
   at DynamicExpresso.Parsing.Parser.ParseConditionalAnd()
   at DynamicExpresso.Parsing.Parser.ParseConditionalOr()
   at DynamicExpresso.Parsing.Parser.ParseConditional()
   at DynamicExpresso.Parsing.Parser.ParseAssignment()
   at DynamicExpresso.Parsing.Parser.ParseExpressionSegment()
   at DynamicExpresso.Parsing.Parser.ParseExpressionSegment(Type returnType)
   at DynamicExpresso.Parsing.Parser.Parse()
   at DynamicExpresso.Interpreter.ParseAsLambda(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Parse(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Eval(String expressionText, Type expressionType, Parameter[] parameters)
   at DynamicExpresso.Interpreter.Eval[T](String expressionText, Parameter[] parameters)
   at Program.Main()
```

Reproduction using the code above is available as [fiddle](https://dotnetfiddle.net/GGrk2F).

**Comment by davideicardi** [comment]
Yes, sorry. For now this is not supported. I appreciate any help/PR.

**Comment by bortolin** [comment]
@marcOcram You must define the indexer to allow to use [] notation on DynamicIndexAccess class.

Try with this code:

`public class DynamicIndexAccess : DynamicObject
	{
		private readonly IReadOnlyDictionary<string, object> _values;

		public DynamicIndexAccess()
		{
			var values = new Dictionary<string, object>();
			values.Add("Hello", "Hello World!");
			_values = values;
		}

		// Add this for use [] notation
		public object this[string index]
		{
			get { return _values[index]; }
		}

		public override bool TryGetIndex(GetIndexBinder binder, object[] indexes, out object result)
		{
			return _values.TryGetValue((string)indexes[0], out result);
		}

		public override bool TryGetMember(GetMemberBinder binder, out object result)
		{
			return _values.TryGetValue(binder.Name, out result);
		}
	}`

**Comment by marcOcram** [comment]
@bortolin yes, that works but somehow goes against the use of `TryGetIndex` of `DynamicObject`.
Nevertheless it is a workaround that works. Thanks.

The only downside is that I expect (from a callers point of view) a `RuntimeBinderException` if I try to access an unknown index. In this case a `KeyNotFoundException` would be thrown (or any other exception, depending on the implementation).

**Comment by bortolin** [comment]
@marcOcram I have the same problem in one of my project ad i use a code like this:

```csharp
using DynamicExpresso;
using System;
using System.Dynamic;
using System.Collections.Generic;

namespace TestExp
{
    class Program
    {
		public class Globals
		{
			private readonly DynamicIndexAccess<string> _values = new DynamicIndexAccess<string>("");
			
			public dynamic Values { get { return _values; } }
		}

		public class DynamicIndexAccess<T> : DynamicObject
		{
			private readonly IDictionary<string, T> _values;
			private T _defaultvalue;

			public DynamicIndexAccess(T defaultvalue)
			{
				_values = new Dictionary<string, T>();
				_defaultvalue = defaultvalue;
			}

			// Add this for use [] notation
			public T this[string index]
			{
				get{
						T retval;
						if (_values.TryGetValue(index,out retval)) return retval;
					return _defaultvalue;
				}
			}

			public override bool TryGetIndex(GetIndexBinder binder, object[] indexes, out object result)
			{
				T val;

				if (_values.TryGetValue((string)indexes[0], out val))
					result = val;
				else
					result = _defaultvalue;
         
				return true;
			}

			public override bool TryGetMember(GetMemberBinder binder, out object result)
			{
				T val;

				if (_values.TryGetValue(binder.Name, out val))
					result = val;
				else
					result = _defaultvalue;

				return true;
			}

            public override bool TrySetIndex(SetIndexBinder binder, object[] indexes, object value)
            {
				_values.Add((string)indexes[0], (T)value);
				return true;
            }
        }

		public static void Main()
		{
			Globals globals = new Globals();

			globals.Values["Hello"] = "Hello World!";

			Interpreter interpreter = new Interpreter()
				.SetVariable("Values", globals.Values);

			// runs
			Console.WriteLine(globals.Values.Hello);
			// runs
			Console.WriteLine(interpreter.Eval<string>("Values.Hello"));
			// runs
			Console.WriteLine(globals.Values["Hello"]);
			// fails
			Console.WriteLine(interpreter.Eval<string>("Values[\"Hello\"]"));

			// Try missing index
			// runs
			Console.WriteLine(globals.Values.SomeKey);
			// runs
			Console.WriteLine(interpreter.Eval<string>("Values.SomeKey"));
			// runs
			Console.WriteLine(globals.Values["SomeKey"]);
			// fails
			Console.WriteLine(interpreter.Eval<string>("Values[\"SomeKey\"]"));
		}
	}
}
